### ISSUE TITLE
Solicitud de Descarga

### ISSUE THREAD

**Issue by ivanporras** [luisiturrios/python-cfdiclient#2]
Al intentar hacer la solicitud de descarga con el token generado, marca esta excepcion. Alguna idea?

Traceback (most recent call last):
  File "solita_descarga_sat.py", line 22, in <module>
    result = descarga.solicitar_descarga(token, rfc_solicitante, fecha_inicial, fecha_final, rfc_emisor=rfc_emisor)
  File "/home/ivan/.local/lib/python2.7/site-packages/cfdiclient/solicitadescarga.py", line 104, in solicitar_descarga
    rfc_solicitante, fecha_inicial, fecha_final, rfc_emisor, rfc_receptor, tipo_solicitud
  File "/home/ivan/.local/lib/python2.7/site-packages/cfdiclient/solicitadescarga.py", line 92, in __generar_soapreq__
    x509issuername.text = self.fiel.cer_issuer()
  File "src/lxml/etree.pyx", line 1023, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 734, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 722, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1527, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by luisiturrios** [comment]
Tiene ese error en Python 2 utiliza Python 3.
Si no puedes utilizar python3 agrega self.fiel.cer_issuer().encode('utf-8') en el archivo fiel.py

**Comment by ivanporras** [comment]
Funciona muchas gracias!
